repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
    -   id: flake8
        args: [--max-line-length=120]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: fix-encoding-pragma
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
