# Build machines configs.
machine-python3: &machine-python3
  docker:
    - image: circleci/python:3.6.6

# Individual (shared) steps.
step_checkout_repo: &step_checkout_repo
  checkout

step_install_requirements_for_smoke_tests: &step_install_requirements_for_smoke_tests
  run:
    name: Create virtualenv and install dependencies
    command: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements_smoke.txt

step_run_smoke_tests: &step_run_smoke_tests
  run:
    name: Run smoke tests
    command: |
      . venv/bin/activate
      python docker/env_writer.py --env=${TEST_ENV} --config=./docker/env.json
      source ./docker/.env_with_export
      make smoke_tests

# List of steps
steps_smoke_tests: &steps_smoke_tests
  steps:
    - *step_checkout_repo
    - *step_install_requirements_for_smoke_tests
    - *step_run_smoke_tests
    - store_test_results:
        path: ./tests/smoke/reports
    - store_artifacts:
        path: ./tests/smoke/reports

# list of all jobs
version: 2
jobs:
  smoke_tests_dev:
    <<: *machine-python3
    working_directory: ~/directory-tests
    environment:
      TEST_ENV: "dev"
    <<: *steps_smoke_tests

  smoke_tests_stage:
    <<: *machine-python3
    working_directory: ~/directory-tests
    environment:
      TEST_ENV: "stage"
    <<: *steps_smoke_tests


workflows:
  version: 2

  run_all_tests_on_dev:
    jobs:
      - smoke_tests_dev

  run_all_tests_on_stage:
    jobs:
      - smoke_tests_stage
