version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - checkout
      - save_cache:
          key: cached-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/directory-tests

  smoke_tests_requirements:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_smoke.txt
      - save_cache:
          key: smoke-tests-dependency-cache-{{ .Revision }}
          paths:
            - ~/directory-tests/venv

  smoke_tests:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - smoke-tests-dependency-cache-{{ .Revision }}
      - run:
          name: Run smoke tests
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env.json
            source ./docker/.env_with_export;
            make smoke_tests
      - store_test_results:
          path: ./tests/smoke/reports
      - store_artifacts:
          path: ./tests/smoke/reports

  smoke_tests_links_checker:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - smoke-tests-dependency-cache-{{ .Revision }}
      - run:
          name: Run link checker tests
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env.json
            source ./docker/.env_with_export;
            make smoke_tests_links_checker

  exred_tests_requirements:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_exred.txt
            nodeenv -p
            npm install -g junit-merge@1.2.3
      - run:
          name: Install Heroku-CLI to project root dir
          command: |
            wget -q https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
            tar -xzf heroku.tar.gz
            mkdir -p ./heroku-cli
            tar -xzf heroku.tar.gz --strip-components 1 -C ./heroku-cli
            rm -fr heroku.tar.gz
            ln -s ./heroku-cli/bin/heroku ./heroku
            heroku -v
      - save_cache:
          key: exred-tests-dependency-cache-{{ .Revision }}
          paths:
            - ~/directory-tests/heroku-cli
            - ~/directory-tests/heroku


  exred_tests_chrome:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - exred-tests-dependency-cache-{{ .Revision }}
      - run:
          name: Run functional ExRed tests in Chrome
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env_exred.json
            source ./docker/.env_with_export;
            BROWSERS=Chrome VERSIONS=63.0 make exred_browserstack
      - run:
          name: Merge JUnit XML reports
          when: always
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ./tests/exred/reports
            junit-merge *.xml -o merged.xml
            ls *.xml | grep -v merged.xml | xargs rm
      - store_test_results:
          path: ./tests/exred/reports
      - store_artifacts:
          path: ./tests/exred/reports

  exred_tests_firefox:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - exred-tests-dependency-cache-{{ .Revision }}
      - run:
          name: Run functional ExRed tests in Firefox
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env_exred.json
            source ./docker/.env_with_export;
            BROWSERS=Firefox VERSIONS=57.0 make exred_browserstack
      - run:
          name: Merge JUnit XML reports
          when: always
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ./tests/exred/reports
            junit-merge *.xml -o merged.xml
            ls *.xml | grep -v merged.xml | xargs rm
      - store_test_results:
          path: ./tests/exred/reports
      - store_artifacts:
          path: ./tests/exred/reports

  functional_tests_requirements:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_functional.txt
            python ./docker/env_writer.py ./docker/env.json
            nodeenv -p
            npm install -g junit-merge@1.2.3
      - save_cache:
          key: dependency-cache-{{ .Revision }}
          paths:
            - ~/directory-tests/venv
            - ~/directory-tests/docker/.env_with_export
            - ~/directory-tests/docker/.env_without_export

  fab_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ .Revision }}
      - run:
          name: Install Heroku-CLI
          command: |
            wget -q https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
            tar -xzf heroku.tar.gz
            mkdir -p /usr/local/lib /usr/local/bin
            sudo mv heroku-cli-v6.*-linux-x64 /usr/local/lib/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/bin/heroku
            heroku -v
            which heroku
            rm -fr heroku.tar.gz
      - run:
          name: Run FAB functional tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env_with_export;
            FEATURE_DIR=fab make functional_tests_feature_dir
      - run:
          name: Merge JUnit XML reports
          when: always
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ./tests/functional/reports
            junit-merge *.xml -o merged.xml
            ls *.xml | grep -v merged.xml | xargs rm
      - store_test_results:
          path: ./tests/functional/reports
      - store_artifacts:
          path: ./tests/functional/reports

  fas_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ .Revision }}
      - run:
          name: Install Heroku-CLI
          command: |
            wget -q https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
            tar -xzf heroku.tar.gz
            mkdir -p /usr/local/lib /usr/local/bin
            sudo mv heroku-cli-v6.*-linux-x64 /usr/local/lib/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/bin/heroku
            heroku -v
            rm -fr heroku.tar.gz
      - run:
          name: Run FAS functional tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env_with_export;
            FEATURE_DIR=fas make functional_tests_feature_dir
      - run:
          name: Merge JUnit XML reports
          when: always
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ./tests/functional/reports
            junit-merge *.xml -o merged.xml
            ls *.xml | grep -v merged.xml | xargs rm
      - store_test_results:
          path: ./tests/functional/reports
      - store_artifacts:
          path: ./tests/functional/reports

  sso_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ .Revision }}
      - run:
          name: Install Heroku-CLI
          command: |
            wget -q https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
            tar -xzf heroku.tar.gz
            mkdir -p /usr/local/lib /usr/local/bin
            sudo mv heroku-cli-v6.*-linux-x64 /usr/local/lib/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/bin/heroku
            heroku -v
            rm -fr heroku.tar.gz
      - run:
          name: Run SSO functional tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env_with_export;
            FEATURE_DIR=sso make functional_tests_feature_dir
      - run:
          name: Merge JUnit XML reports
          when: always
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ./tests/functional/reports
            junit-merge *.xml -o merged.xml
            ls *.xml | grep -v merged.xml | xargs rm
      - store_test_results:
          path: ./tests/functional/reports
      - store_artifacts:
          path: ./tests/functional/reports

  sud_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - dependency-cache-{{ .Revision }}
      - run:
          name: Install Heroku-CLI
          command: |
            wget -q https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz -O heroku.tar.gz
            tar -xzf heroku.tar.gz
            mkdir -p /usr/local/lib /usr/local/bin
            sudo mv heroku-cli-v6.*-linux-x64 /usr/local/lib/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
            sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/bin/heroku
            heroku -v
            rm -fr heroku.tar.gz
      - run:
          name: Run SUD functional tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env_with_export;
            FEATURE_DIR=sud make functional_tests_feature_dir
      - run:
          name: Merge JUnit XML reports
          when: always
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd ./tests/functional/reports
            junit-merge *.xml -o merged.xml
            ls *.xml | grep -v merged.xml | xargs rm
      - store_test_results:
          path: ./tests/functional/reports
      - store_artifacts:
          path: ./tests/functional/reports


workflows:
  version: 2
  run_all_tests:
    jobs:
      - checkout_code
      - functional_tests_requirements:
          requires:
            - checkout_code
      - smoke_tests_requirements:
          requires:
            - checkout_code
      - exred_tests_requirements:
          requires:
            - checkout_code
      - smoke_tests:
          requires:
            - checkout_code
            - smoke_tests_requirements
      - smoke_tests_links_checker:
          requires:
            - checkout_code
            - smoke_tests_requirements
      - exred_tests_chrome:
          requires:
            - smoke_tests
            - exred_tests_requirements
      - exred_tests_firefox:
          requires:
            - smoke_tests
            - exred_tests_requirements
      - fab_functional_tests:
          requires:
            - smoke_tests
            - functional_tests_requirements
      - fas_functional_tests:
          requires:
            - smoke_tests
            - functional_tests_requirements
      - sso_functional_tests:
          requires:
            - smoke_tests
            - functional_tests_requirements
      - sud_functional_tests:
          requires:
            - smoke_tests
            - functional_tests_requirements
