version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - checkout
      - save_cache:
          key: cached-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/directory-tests

  fabs_smoke_tests:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_smoke.txt
      - run:
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env.json
            source ./docker/.env;
            make smoke_tests

  exred_functional_tests_chrome:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_exred.txt
      - run:
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env_exred.json
            source ./docker/.env;
            BROWSERS=Chrome VERSIONS=62.0 make exred_browserstack

  exred_functional_tests_firefox:
    docker:
      - image: circleci/python:3.5.3
    working_directory: ~/directory-tests
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_exred.txt
      - run:
          command: |
            . venv/bin/activate
            python ./docker/env_writer.py ./docker/env_exred.json
            source ./docker/.env;
            BROWSERS=Firefox VERSIONS=56.0 make exred_browserstack

  fabs_integration_tests_fab:
  functional_tests_requirements:
    docker:
      - image: circleci/python:3.5.3
    steps:
      - restore_cache:
          keys:
            - cached-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_functional.txt
            python ./docker/env_writer.py ./docker/env.json
      - save_cache:
          key: dependency-cache-{{ checksum "requirements_functional.txt" }}
          paths:
            - ~/directory-tests

  fab_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "requirements_functional.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env;
            FEATURE_DIR=fab make functional_tests_feature_dir

  fabs_integration_tests_sso:
    docker:
      - image: circleci/python:3.5.3
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "requirements_functional.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env;
            FEATURE_DIR=fas make functional_tests_feature_dir

  sso_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "requirements_functional.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env;
            FEATURE_DIR=sso make functional_tests_feature_dir

  sud_functional_tests:
    docker:
      - image: circleci/python:3.5.3
    steps:
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "requirements_functional.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            source ./docker/.env;
            FEATURE_DIR=sud make functional_tests_feature_dir


workflows:
  version: 2
  run_all_tests:
    jobs:
      - checkout_code
      - fabs_smoke_tests:
          requires:
            - checkout_code
      - exred_functional_tests_chrome:
          requires:
            - fabs_smoke_tests
      - exred_functional_tests_firefox:
          requires:
            - fabs_smoke_tests
      - fabs_integration_tests_fab:
          requires:
            - fabs_smoke_tests
      - fabs_integration_tests_fas:
          requires:
            - fabs_smoke_tests
      - fabs_integration_tests_sso:
          requires:
            - fabs_smoke_tests
